create table "public"."hoge" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."hoge" enable row level security;

CREATE UNIQUE INDEX hoge_pkey ON public.hoge USING btree (id);

alter table "public"."hoge" add constraint "hoge_pkey" PRIMARY KEY using index "hoge_pkey";

grant delete on table "public"."hoge" to "anon";

grant insert on table "public"."hoge" to "anon";

grant references on table "public"."hoge" to "anon";

grant select on table "public"."hoge" to "anon";

grant trigger on table "public"."hoge" to "anon";

grant truncate on table "public"."hoge" to "anon";

grant update on table "public"."hoge" to "anon";

grant delete on table "public"."hoge" to "authenticated";

grant insert on table "public"."hoge" to "authenticated";

grant references on table "public"."hoge" to "authenticated";

grant select on table "public"."hoge" to "authenticated";

grant trigger on table "public"."hoge" to "authenticated";

grant truncate on table "public"."hoge" to "authenticated";

grant update on table "public"."hoge" to "authenticated";

grant delete on table "public"."hoge" to "service_role";

grant insert on table "public"."hoge" to "service_role";

grant references on table "public"."hoge" to "service_role";

grant select on table "public"."hoge" to "service_role";

grant trigger on table "public"."hoge" to "service_role";

grant truncate on table "public"."hoge" to "service_role";

grant update on table "public"."hoge" to "service_role";


