create table "public"."saka" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."saka" enable row level security;

CREATE UNIQUE INDEX saka_pkey ON public.saka USING btree (id);

alter table "public"."saka" add constraint "saka_pkey" PRIMARY KEY using index "saka_pkey";

grant delete on table "public"."saka" to "anon";

grant insert on table "public"."saka" to "anon";

grant references on table "public"."saka" to "anon";

grant select on table "public"."saka" to "anon";

grant trigger on table "public"."saka" to "anon";

grant truncate on table "public"."saka" to "anon";

grant update on table "public"."saka" to "anon";

grant delete on table "public"."saka" to "authenticated";

grant insert on table "public"."saka" to "authenticated";

grant references on table "public"."saka" to "authenticated";

grant select on table "public"."saka" to "authenticated";

grant trigger on table "public"."saka" to "authenticated";

grant truncate on table "public"."saka" to "authenticated";

grant update on table "public"."saka" to "authenticated";

grant delete on table "public"."saka" to "service_role";

grant insert on table "public"."saka" to "service_role";

grant references on table "public"."saka" to "service_role";

grant select on table "public"."saka" to "service_role";

grant trigger on table "public"."saka" to "service_role";

grant truncate on table "public"."saka" to "service_role";

grant update on table "public"."saka" to "service_role";


