create table "public"."fuga" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."fuga" enable row level security;

CREATE UNIQUE INDEX fuga_pkey ON public.fuga USING btree (id);

alter table "public"."fuga" add constraint "fuga_pkey" PRIMARY KEY using index "fuga_pkey";

grant delete on table "public"."fuga" to "anon";

grant insert on table "public"."fuga" to "anon";

grant references on table "public"."fuga" to "anon";

grant select on table "public"."fuga" to "anon";

grant trigger on table "public"."fuga" to "anon";

grant truncate on table "public"."fuga" to "anon";

grant update on table "public"."fuga" to "anon";

grant delete on table "public"."fuga" to "authenticated";

grant insert on table "public"."fuga" to "authenticated";

grant references on table "public"."fuga" to "authenticated";

grant select on table "public"."fuga" to "authenticated";

grant trigger on table "public"."fuga" to "authenticated";

grant truncate on table "public"."fuga" to "authenticated";

grant update on table "public"."fuga" to "authenticated";

grant delete on table "public"."fuga" to "service_role";

grant insert on table "public"."fuga" to "service_role";

grant references on table "public"."fuga" to "service_role";

grant select on table "public"."fuga" to "service_role";

grant trigger on table "public"."fuga" to "service_role";

grant truncate on table "public"."fuga" to "service_role";

grant update on table "public"."fuga" to "service_role";


