create table "public"."sumaho" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."sumaho" enable row level security;

CREATE UNIQUE INDEX sumaho_pkey ON public.sumaho USING btree (id);

alter table "public"."sumaho" add constraint "sumaho_pkey" PRIMARY KEY using index "sumaho_pkey";

grant delete on table "public"."sumaho" to "anon";

grant insert on table "public"."sumaho" to "anon";

grant references on table "public"."sumaho" to "anon";

grant select on table "public"."sumaho" to "anon";

grant trigger on table "public"."sumaho" to "anon";

grant truncate on table "public"."sumaho" to "anon";

grant update on table "public"."sumaho" to "anon";

grant delete on table "public"."sumaho" to "authenticated";

grant insert on table "public"."sumaho" to "authenticated";

grant references on table "public"."sumaho" to "authenticated";

grant select on table "public"."sumaho" to "authenticated";

grant trigger on table "public"."sumaho" to "authenticated";

grant truncate on table "public"."sumaho" to "authenticated";

grant update on table "public"."sumaho" to "authenticated";

grant delete on table "public"."sumaho" to "service_role";

grant insert on table "public"."sumaho" to "service_role";

grant references on table "public"."sumaho" to "service_role";

grant select on table "public"."sumaho" to "service_role";

grant trigger on table "public"."sumaho" to "service_role";

grant truncate on table "public"."sumaho" to "service_role";

grant update on table "public"."sumaho" to "service_role";


